export interface Activity extends Record<string, any> {
  title: string;
  description: string;
  src: string;
  href: string;
}
export interface Activities extends Record<string, any> {
  title: string;
  items: Activity[];
}

export const activities : Activities[] =
  [
    {
    title: 'freebies',
    items: [
      {
        title: 'Soup Kitchen',
        description: 'Free food for the homeless',
        src: '/soupkitchen.gif',
        href: 'http://www.neopets.com/soupkitchen.phtml',
      },
      {
        title: 'Giant Jelly',
        description: 'Free food for the homeless',
        src: 'https://images.neopets.com/games/betterthanyou/contestant505.gif',
        href: 'http://www.neopets.com/soupkitchen.phtml',
      },
      {
        title: 'Giant Omelette',
        description: 'Free food for the homeless',
        src: 'https://images.neopets.com/af13h43uw1/games/lg_7.jpg',
        href: 'http://www.neopets.com/soupkitchen.phtml',
      },
      {
        title: 'Bank Interest',
        description: 'Free food for the homeless',
        src: 'https://images.neopets.com/pin/bank_pin_mgr_150.gif',
        href: 'http://www.neopets.com/soupkitchen.phtml',
      },
      {
        title: 'The Money Tree',
        description: 'Free food for the homeless',
        src: 'https://images.neopets.com/games/tradingcards/lg_136.gif',
        href: 'http://www.neopets.com/soupkitchen.phtml',
      },
      {
        title: 'Second Hand Shoppe',
        description: 'Free food for the homeless',
        src: 'https://images.neopets.com/nt/ntimages/314_2ndhand_shoppe.gif',
        href: 'http://www.neopets.com/soupkitchen.phtml',
      },
      {
        title: 'Rubbish Dump',
        description: 'Free food for the homeless',
        src: 'https://images.neopets.com/nt/ntimages/179_shoyru_dump.gif',
        href: 'http://www.neopets.com/soupkitchen.phtml',
      },
      {
        title: 'Altador Plot Prizes',
        description: 'Free food for the homeless',
        src: 'https://images.neopets.com/altador/council/altador_closeup_dd32449a91.gif',
        href: 'http://www.neopets.com/soupkitchen.phtml',
      },
      {
        title: 'Shop Till',
        description: 'Free food for the homeless',
        src: 'https://images.neopets.com/nt/ntimages/242_draik_np.gif',
        href: 'http://www.neopets.com/soupkitchen.phtml',
      },
      {
        title: 'Shop of Offers',
        description: 'Free food for the homeless',
        src: 'https://images.neopets.com/nt/ntimages/199_slorg_sale.gif',
        href: 'http://www.neopets.com/soupkitchen.phtml',
      },
      {
        title: 'Favorite Games',
        description: 'Free food for the homeless',
        src: 'https://images.neopets.com/nt/ntimages/242_draik_np.gif',
        href: 'http://www.neopets.com/soupkitchen.phtml',
      },
      {
        title: 'PetPetPark Daily',
        description: 'Free food for the homeless',
        src: 'https://images.neopets.com/games/clicktoplay/icon_1054.gif',
        href: 'http://www.neopets.com/soupkitchen.phtml',
      },
      {
        title: 'Monthly Freebies',
        description: 'Free food for the homeless',
        src: '/soupkitchen.gif',
        href: 'http://www.neopets.com/soupkitchen.phtml',
      },
      {
        title: 'Movie Central',
        description: 'Free food for the homeless',
        src: 'https://images.neopets.com/games/clicktoplay/ctp_380.gif',
        href: 'http://www.neopets.com/soupkitchen.phtml',
      },
      {
        title: 'Obsidian Quarry',
        description: 'Free food for the homeless',
        src: '/soupkitchen.gif',
        href: 'http://www.neopets.com/soupkitchen.phtml',
      },
      {
        title: 'Apple Bobbing',
        description: 'Free food for the homeless',
        src: '/soupkitchen.gif',
        href: 'http://www.neopets.com/soupkitchen.phtml',
      },
      {
        title: 'Anchor Management',
        description: 'Free food for the homeless',
        src: '/soupkitchen.gif',
        href: 'http://www.neopets.com/soupkitchen.phtml',
      },
      {
        title: 'Mysterious Negg Cave',
        description: 'Free food for the homeless',
        src: '/soupkitchen.gif',
        href: 'http://www.neopets.com/soupkitchen.phtml',
      },
      {
        title: 'Obelisk Plot',
        description: 'Free food for the homeless',
        src: '/soupkitchen.gif',
        href: 'http://www.neopets.com/soupkitchen.phtml',
      },
      {
        title: 'Grave Danger',
        description: 'Free food for the homeless',
        src: '/soupkitchen.gif',
        href: 'http://www.neopets.com/soupkitchen.phtml',
      },
      {
        title: 'Kiko Pop',
        description: 'Free food for the homeless',
        src: '/soupkitchen.gif',
        href: 'http://www.neopets.com/soupkitchen.phtml',
      },
    ]
  },
  {
    title: 'wheels',
    items: [
      {
        title: 'Wheel of Mediocrity',
        description: 'Free food for the homeless',
        src: '/vercel.svg',
        href: 'https://vercel.com',
      },
      {
        title: 'Wheel of Excitement',
        description: 'Free food for the homeless',
        src: '/vercel.svg',
        href: 'https://vercel.com',
      },
      {
        title: 'Wheel of Misfortune',
        description: 'Free food for the homeless',
        src: '/vercel.svg',
        href: 'https://vercel.com',
      },
      {
        title: 'Wheel of Knowledge',
        description: 'Free food for the homeless',
        src: '/vercel.svg',
        href: 'https://vercel.com',
      },
      {
        title: 'Wheel of Monotony',
        description: 'Free food for the homeless',
        src: '/vercel.svg',
        href: 'https://vercel.com',
      },
      {
        title: 'Wheel of Extravagance',
        description: 'Free food for the homeless',
        src: '/vercel.svg',
        href: 'https://vercel.com',
      },
      {
        title: 'NC Archives Wheel',
        description: 'Free food for the homeless',
        src: '/vercel.svg',
        href: 'https://vercel.com',
      },
    ],
  },
  {
    title: 'Scratchcards',
    items: [
      {
      title: 'Winter Kiosk',
      description: 'Free food for the homeless',
      src: '/vercel.svg',
      href: 'https://vercel.com',
    },
    {
      title: 'Spooky Kiosk',
      description: 'Free food for the homeless',
      src: '/vercel.svg',
      href: 'https://vercel.com',
    },
    {
      title: 'Desert Kiosk',
      description: 'Free food for the homeless',
      src: '/vercel.svg',
      href: 'https://vercel.com',
    },
    ],
  },
  {
    title: 'essentials',
    items: [
      {
      title: 'Tombola',
      description: 'Free food for the homeless',
      src: '/vercel.svg',
      href: 'https://vercel.com',
    },
    {
      title: 'Snowager',
      description: 'Free food for the homeless',
      src: '/vercel.svg',
      href: 'https://vercel.com',
    },
    {
      title: 'Guess the Marrow',
      description: 'Free food for the homeless',
      src: '/vercel.svg',
      href: 'https://vercel.com',
    },
    {
      title: 'Wise Old King',
      description: 'Free food for the homeless',
      src: '/vercel.svg',
      href: 'https://vercel.com',
    },
    {
      title: 'Grumpy Old King',
      description: 'Free food for the homeless',
      src: '/vercel.svg',
      href: 'https://vercel.com',
    },
    {
      title: 'Deserted Tomb',
      description: 'Free food for the homeless',
      src: '/vercel.svg',
      href: 'https://vercel.com',
    },
    {
      title: 'Fruit Machine',
      description: 'Free food for the homeless',
      src: '/vercel.svg',
      href: 'https://vercel.com',
    },
    {
      title: 'Coltzan\'s Shrine',
      description: 'Free food for the homeless',
      src: '/vercel.svg',
      href: 'https://vercel.com',
    },
    {
      title: 'Deadly Dice',
      description: 'Free food for the homeless',
      src: '/vercel.svg',
      href: 'https://vercel.com',
    },
    {
      title: 'Kreludor Meteor',
      description: 'Free food for the homeless',
      src: '/vercel.svg',
      href: 'https://vercel.com',
    },
    {
      title: 'TDMBGPOP',
      description: 'Free food for the homeless',
      src: '/vercel.svg',
      href: 'https://vercel.com',
    },
    {
      title: 'Ye Olde Fishing Vortex',
      description: 'Free food for the homeless',
      src: '/vercel.svg',
      href: 'https://vercel.com',
    },
    {
      title: 'Hide n\' Seek',
      description: 'Free food for the homeless',
      src: '/vercel.svg',
      href: 'https://vercel.com',
    },
    {
      title: 'Quasalan Expellibox',
      description: 'Free food for the homeless',
      src: '/vercel.svg',
      href: 'https://vercel.com',
    },
    {
      title: 'Lunar Temple',
      description: 'Free food for the homeless',
      src: '/vercel.svg',
      href: 'https://vercel.com',
    },
    {
      title: 'Potato Counter',
      description: 'Free food for the homeless',
      src: '/vercel.svg',
      href: 'https://vercel.com',
    },
    {
      title: 'Forgotten Shore',
      description: 'Free food for the homeless',
      src: '/vercel.svg',
      href: 'https://vercel.com',
    },
    {
      title: 'Healing Springs',
      description: 'Free food for the homeless',
      src: '/vercel.svg',
      href: 'https://vercel.com',
    },
    {
      title: 'Battledome Daily Prizes',
      description: 'Free food for the homeless',
      src: '/vercel.svg',
      href: 'https://vercel.com',
    },
    ]
  },
  {
    title: 'neopoints',
    items: [
      {
      title: 'Smuggler\s Cove',
      description: 'Free food for the homeless',
      src: '/vercel.svg',
      href: 'https://vercel.com',
    },
    {
      title: 'Garage Sale',
      description: 'Free food for the homeless',
      src: '/vercel.svg',
      href: 'https://vercel.com',
    },
    {
      title: 'Buried Treasure',
      description: 'Free food for the homeless',
      src: '/vercel.svg',
      href: 'https://vercel.com',
    },
    {
      title: 'Poogle Racing',
      description: 'Free food for the homeless',
      src: '/vercel.svg',
      href: 'https://vercel.com',
    },
    {
      title: 'Turdle Racing',
      description: 'Free food for the homeless',
      src: '/vercel.svg',
      href: 'https://vercel.com',
    },
    {
      title: 'Lever of Doom',
      description: 'Free food for the homeless',
      src: '/vercel.svg',
      href: 'https://vercel.com',
    },
    {
      title: 'Grarrl Keno',
      description: 'Free food for the homeless',
      src: '/vercel.svg',
      href: 'https://vercel.com',
    },
    {
      title: 'Neopian Lottery',
      description: 'Free food for the homeless',
      src: '/vercel.svg',
      href: 'https://vercel.com',
    },
    {
      title: 'Test Your Strength',
      description: 'Free food for the homeless',
      src: '/vercel.svg',
      href: 'https://vercel.com',
    },
    {
      title: 'Wishing Well',
      description: 'Free food for the homeless',
      src: '/vercel.svg',
      href: 'https://vercel.com',
    },
    {
      title: 'Coconut Shy',
      description: 'Free food for the homeless',
      src: '/vercel.svg',
      href: 'https://vercel.com',
    },
    {
      title: 'Bagatelle',
      description: 'Free food for the homeless',
      src: '/vercel.svg',
      href: 'https://vercel.com',
    },
    {
      title: 'Cork Gun Gallery',
      description: 'Free food for the homeless',
      src: '/vercel.svg',
      href: 'https://vercel.com',
    },
    {
      title: 'Double or Nothing',
      description: 'Free food for the homeless',
      src: '/vercel.svg',
      href: 'https://vercel.com',
    },
    {
      title: 'Kiss the Mortog',
      description: 'Free food for the homeless',
      src: '/vercel.svg',
      href: 'https://vercel.com',
    },
    {
      title: 'Cheeseroller',
      description: 'Free food for the homeless',
      src: '/vercel.svg',
      href: 'https://vercel.com',
    },
    {
      title: 'Pick Your Own',
      description: 'Free food for the homeless',
      src: '/vercel.svg',
      href: 'https://vercel.com',
    },
    {
      title: 'Food Club',
      description: 'Free food for the homeless',
      src: '/vercel.svg',
      href: 'https://vercel.com',
    },
    {
      title: 'Stock Market',
      description: 'Free food for the homeless',
      src: '/vercel.svg',
      href: 'https://vercel.com',
    },
    {
      title: 'Snow Wars',
      description: 'Free food for the homeless',
      src: '/vercel.svg',
      href: 'https://vercel.com',
    },
    {
      title: 'Almost Abandoned Attic',
      description: 'Free food for the homeless',
      src: '/vercel.svg',
      href: 'https://vercel.com',
    },
    {
      title: 'Faerie Caverns',
      description: 'Free food for the homeless',
      src: '/vercel.svg',
      href: 'https://vercel.com',
    },
    {
      title: 'Cheat!',
      description: 'Free food for the homeless',
      src: '/vercel.svg',
      href: 'https://vercel.com',
    },
    {
      title: 'Scorchy Slots',
      description: 'Free food for the homeless',
      src: '/vercel.svg',
      href: 'https://vercel.com',
    },
    {
      title: 'Gormball',
      description: 'Free food for the homeless',
      src: '/vercel.svg',
      href: 'https://vercel.com',
    },
    {
      title: 'Dice-a-Roo',
      description: 'Free food for the homeless',
      src: '/vercel.svg',
      href: 'https://vercel.com',
    },
    {
      title: 'Toy Repair Shop',
      description: 'Free food for the homeless',
      src: '/vercel.svg',
      href: 'https://vercel.com',
    },
    ],
  },
  {
    title: 'training',
    items: [
      {
        title: 'Codestone Training',
        description: 'Free food for the homeless',
        src: '/vercel.svg',
        href: 'https://vercel.com',
      },
      {
        title: 'Dubloon Training',
        description: 'Free food for the homeless',
        src: '/vercel.svg',
        href: 'https://vercel.com',
      },
      {
        title: 'Ninja Training School',
        description: 'Free food for the homeless',
        src: '/vercel.svg',
        href: 'https://vercel.com',
      },
    ],
  },
  {
    title: 'Other',
    items: [
      {
        title: 'Turmaculus',
        description: 'Free food for the homeless',
        src: '/vercel.svg',
        href: 'https://vercel.com',
      },
      {
        title: 'Symol Hole',
        description: 'Free food for the homeless',
        src: '/vercel.svg',
        href: 'https://vercel.com',
      },
      {
        title: 'Laboratory Ray',
        description: 'Free food for the homeless',
        src: '/vercel.svg',
        href: 'https://vercel.com',
      },
      {
        title: 'PetPet Laboratory Ray',
        description: 'Free food for the homeless',
        src: '/vercel.svg',
        href: 'https://vercel.com',
      },
      {
        title: 'Stock Market',
        description: 'Free food for the homeless',
        src: '/vercel.svg',
        href: 'https://vercel.com',
      },
      {
        title: 'Neopian News',
        description: 'Free food for the homeless',
        src: '/vercel.svg',
        href: 'https://vercel.com',
      },
      {
        title: 'Neopian Times',
        description: 'Free food for the homeless',
        src: '/vercel.svg',
        href: 'https://vercel.com',
      },
      {
        title: 'Trading Post',
        description: 'Free food for the homeless',
        src: '/vercel.svg',
        href: 'https://vercel.com',
      },
      {
        title: 'Auction House',
        description: 'Free food for the homeless',
        src: '/vercel.svg',
        href: 'https://vercel.com',
      },
      {
        title: 'Employment Agency',
        description: 'Free food for the homeless',
        src: '/vercel.svg',
        href: 'https://vercel.com',
      },
      {
        title: 'Neolodge',
        description: 'Free food for the homeless',
        src: '/vercel.svg',
        href: 'https://vercel.com',
      },
      {
        title: 'Featured Band',
        description: 'Free food for the homeless',
        src: '/vercel.svg',
        href: 'https://vercel.com',
      },
      {
        title: 'Haiku',
        description: 'Free food for the homeless',
        src: '/vercel.svg',
        href: 'https://vercel.com',
      },
      {
        title: 'Island Mystic',
        description: 'Free food for the homeless',
        src: '/vercel.svg',
        href: 'https://vercel.com',
      },
      {
        title: 'Golden Dubloon',
        description: 'Free food for the homeless',
        src: '/vercel.svg',
        href: 'https://vercel.com',
      },
      {
        title: 'Kelp Restaurant',
        description: 'Free food for the homeless',
        src: '/vercel.svg',
        href: 'https://vercel.com',
      },
      {
        title: 'Merry Go Round',
        description: 'Free food for the homeless',
        src: '/vercel.svg',
        href: 'https://vercel.com',
      },
      {
        title: 'Tiki Tours',
        description: 'Free food for the homeless',
        src: '/vercel.svg',
        href: 'https://vercel.com',
      },
      {
        title: 'Neomail',
        description: 'Free food for the homeless',
        src: '/vercel.svg',
        href: 'https://vercel.com',
      },
      {
        title: 'Tarla\'s Shop',
        description: 'Free food for the homeless',
        src: '/vercel.svg',
        href: 'https://vercel.com',
      },
      {
        title: 'Tarla\'s Treasures',
        description: 'Free food for the homeless',
        src: '/vercel.svg',
        href: 'https://vercel.com',
      },
      {
        title: 'Multiplayer Competition',
        description: 'Free food for the homeless',
        src: '/vercel.svg',
        href: 'https://vercel.com',
      },
      {
        title: 'Kadoatery',
        description: 'Free food for the homeless',
        src: '/vercel.svg',
        href: 'https://vercel.com',
      },
      {
        title: 'Neggery',
        description: 'Free food for the homeless',
        src: '/vercel.svg',
        href: 'https://vercel.com',
      },
      {
        title: 'Plushie Tycoon',
        description: 'Free food for the homeless',
        src: '/vercel.svg',
        href: 'https://vercel.com',
      },
      {
        title: 'Magma Pool',
        description: 'Free food for the homeless',
        src: '/vercel.svg',
        href: 'https://vercel.com',
      },
      {
        title: 'Tangor\'s Workshop',
        description: 'Free food for the homeless',
        src: '/vercel.svg',
        href: 'https://vercel.com',
      },
      {
        title: 'Cliffhanger',
        description: 'Free food for the homeless',
        src: '/vercel.svg',
        href: 'https://vercel.com',
      },
      {
        title: 'NeoQuest',
        description: 'Free food for the homeless',
        src: '/vercel.svg',
        href: 'https://vercel.com',
      },
      {
        title: 'NeoQuest II',
        description: 'Free food for the homeless',
        src: '/vercel.svg',
        href: 'https://vercel.com',
      },
      {
        title: 'Neocola Machine',
        description: 'Free food for the homeless',
        src: '/vercel.svg',
        href: 'https://vercel.com',
      },
      {
        title: 'Alien Aisha Vending Machine',
        description: 'Free food for the homeless',
        src: '/vercel.svg',
        href: 'https://vercel.com',
      },
    ],
  },
  {
    title: 'quests',
    items: [
      {
        title: 'Illusen\'s Glade',
        description: 'Free food for the homeless',
        src: '/vercel.svg',
        href: 'https://vercel.com',
      },
      {
        title: 'Jhudora\'s Bluff',
        description: 'Free food for the homeless',
        src: '/vercel.svg',
        href: 'https://vercel.com',
      },
      {
        title: 'Brain Tree Quests',
        description: 'Free food for the homeless',
        src: '/vercel.svg',
        href: 'https://vercel.com',
      },
      {
        title: 'Esophagor\'s Quests',
        description: 'Free food for the homeless',
        src: '/vercel.svg',
        href: 'https://vercel.com',
      },
      {
        title: 'Edna\'s Quests',
        description: 'Free food for the homeless',
        src: '/vercel.svg',
        href: 'https://vercel.com',
      },
      {
        title: 'Kitchen Quests',
        description: 'Free food for the homeless',
        src: '/vercel.svg',
        href: 'https://vercel.com',
      },
      {
        title: 'Snow Faerie Quests',
        description: 'Free food for the homeless',
        src: '/vercel.svg',
        href: 'https://vercel.com',
      },
      {
        title: 'Faerie Quests',
        description: 'Free food for the homeless',
        src: '/vercel.svg',
        href: 'https://vercel.com',
      },
      {
        title: 'Coincidence',
        description: 'Free food for the homeless',
        src: '/vercel.svg',
        href: 'https://vercel.com',
      },
    ],
  },
  {
    title: 'contests',
    items: [
      {
        title: 'Lenny Conundrum',
        description: 'Free food for the homeless',
        src: '/vercel.svg',
        href: 'https://vercel.com',
      },
      {
        title: 'Neohome',
        description: 'Free food for the homeless',
        src: '/vercel.svg',
        href: 'https://vercel.com',
      },
      {
        title: 'Gallery',
        description: 'Free food for the homeless',
        src: '/vercel.svg',
        href: 'https://vercel.com',
      },
      {
        title: 'Gourmet Club',
        description: 'Free food for the homeless',
        src: '/vercel.svg',
        href: 'https://vercel.com',
      },
      {
        title: 'Site Spotlight',
        description: 'Free food for the homeless',
        src: '/vercel.svg',
        href: 'https://vercel.com',
      },
      {
        title: 'PetPet Spotlight',
        description: 'Free food for the homeless',
        src: '/vercel.svg',
        href: 'https://vercel.com',
      },
      {
        title: 'Pet Spotlight',
        description: 'Free food for the homeless',
        src: '/vercel.svg',
        href: 'https://vercel.com',
      },
      {
        title: 'Art Gallery',
        description: 'Free food for the homeless',
        src: '/vercel.svg',
        href: 'https://vercel.com',
      },
      {
        title: 'Poem',
        description: 'Free food for the homeless',
        src: '/vercel.svg',
        href: 'https://vercel.com',
      },
      {
        title: 'Better Than You',
        description: 'Free food for the homeless',
        src: '/vercel.svg',
        href: 'https://vercel.com',
      },
      {
        title: 'Neopian Times',
        description: 'Free food for the homeless',
        src: '/vercel.svg',
        href: 'https://vercel.com',
      },
      {
        title: 'Beauty Contest',
        description: 'Free food for the homeless',
        src: '/vercel.svg',
        href: 'https://vercel.com',
      },
      {
        title: 'Caption Contest',
        description: 'Free food for the homeless',
        src: '/vercel.svg',
        href: 'https://vercel.com',
      },
      {
        title: 'Mystery Pic',
        description: 'Free food for the homeless',
        src: '/vercel.svg',
        href: 'https://vercel.com',
      },
      {
        title: 'Story Telling',
        description: 'Free food for the homeless',
        src: '/vercel.svg',
        href: 'https://vercel.com',
      },
      {
        title: 'Customisation',
        description: 'Free food for the homeless',
        src: '/vercel.svg',
        href: 'https://vercel.com',
      },
      {
        title: 'User Lookups',
        description: 'Free food for the homeless',
        src: '/vercel.svg',
        href: 'https://vercel.com',
      },
    ]
  }
]
