export interface Activity extends Record<string, any> {
  title: string;
  description: string;
  src: string;
  href: string;
}
export interface Activities extends Record<string, any> {
  title: string;
  items: Activity[];
}

export const activities : Activities[] =
  [
    {
    title: 'freebies',
    items: [
      {
        title: 'Soup Kitchen',
        description: 'Free food for the homeless',
        src: 'https://images.neopets.com/items/foo_faerie_soupfaeriesoup.gif',
        href: 'http://www.neopets.com/soupkitchen.phtml',
      },
      {
        title: 'Giant Jelly',
        description: 'Giant Jelly',
        src: 'https://images.neopets.com/items/gar_mini_giantjelly.gif',
        href: 'http://www.neopets.com/jelly/jelly.phtml',
      },
      {
        title: 'Giant Omelette',
        description: 'Free food for the homeless',
        src: 'https://images.neopets.com/items/stamp_tyrannia_omelette.gif',
        href: 'http://www.neopets.com/prehistoric/omelette.phtml?type=get_omelette',
      },
      {
        title: 'Bank Interest',
        description: 'Free food for the homeless',
        src: 'https://images.neopets.com/items/toy_bankmanager_skeith.gif',
        href: 'http://www.neopets.com/bank.phtml',
      },
      {
        title: 'The Money Tree',
        description: 'Free food for the homeless',
        src: 'https://images.neopets.com/items/mini_moneytree.gif',
        href: 'http://www.neopets.com/donations.phtml',
      },
      {
        title: 'Second Hand Shoppe',
        description: 'Free food for the homeless',
        src: 'https://images.neopets.com/items/newbie_potatosack.gif',
        href: 'http://www.neopets.com/thriftshoppe/index.phtml',
      },
      {
        title: 'Rubbish Dump',
        description: 'Free food for the homeless',
        src: 'https://images.neopets.com/items/med_booby_6.gif',
        href: 'http://www.neopets.com/medieval/rubbishdump.phtml',
      },
      {
        title: 'Altador Plot Prizes',
        description: 'Only if you completed the Altador plot',
        src: 'https://images.neopets.com/altador/altador_trophy.gif',
        href: 'http://www.neopets.com/altador/council.phtml',
      },
      {
        title: 'Shop Till',
        description: 'Free food for the homeless',
        src: 'https://images.neopets.com/items/sch_mynci_cashregister.gif',
        href: 'http://www.neopets.com/market.phtml?type=till',
      },
      {
        title: 'Shop of Offers',
        description: 'Free food for the homeless',
        src: 'https://images.neopets.com/items/toy_slorgball.gif',
        href: 'http://www.neopets.com/shop_of_offers.phtml?slorg_payout=yes',
      },
      {
        title: 'Favorite Games',
        description: 'Free food for the homeless',
        src: 'https://images.neopets.com/items/boo_dd_ilovegames.gif',
        href: 'http://www.neopets.com/games/favorites.phtml',
      },
      {
        title: 'PetPetPark Daily',
        description: 'Free food for the homeless',
        src: 'https://images.neopets.com/items/toy_pinixy_figure.gif',
        href: 'http://www.neopets.com/petpetpark/daily.phtml',
      },
      {
        title: 'Monthly Freebies',
        description: 'Free food for the homeless',
        src: 'https://images.neopets.com/items/boo_desk_calendar.gif',
        href: 'http://www.neopets.com/freebies/index.phtml',
      },
      {
        title: 'Movie Central',
        description: 'Free food for the homeless',
        src: 'https://images.neopets.com/items/mall_hh_candypopcorn.gif',
        href: 'http://www.neopets.com/moviecentral/index.phtml',
      },
      {
        title: 'Obsidian Quarry',
        description: 'Free food for the homeless',
        src: 'https://items.jellyneo.net/assets/imgs/items/35706.gif',
        href: 'http://www.neopets.com/magma/quarry.phtml',
      },
      {
        title: 'Apple Bobbing',
        description: 'Free food for the homeless',
        src: 'https://images.neopets.com/items/med_applecore.gif',
        href: 'http://www.neopets.com/halloween/applebobbing.phtml?',
      },
      {
        title: 'Anchor Management',
        description: 'Free food for the homeless',
        src: 'https://images.neopets.com/items/fur_pirate_anchor.gif',
        href: 'http://www.neopets.com/pirates/anchormanagement.phtml',
      },
      {
        title: 'Mysterious Negg Cave',
        description: 'Free food for the homeless',
        src: 'https://images.neopets.com/items/foo_cybunny_neggrain.gif',
        href: 'http://www.neopets.com/shenkuu/neggcave/',
      },
      {
        title: 'Obelisk Plot',
        description: 'Free food for the homeless',
        src: 'https://images.neopets.com/items/sta_tyweof2013_myobalstmp.gif',
        href: 'http://www.neopets.com/prehistoric/battleground/',
      },
      {
        title: 'Grave Danger',
        description: 'Free food for the homeless',
        src: 'https://images.neopets.com/items/sta_gd_grave_danger.gif',
        href: 'http://www.neopets.com/halloween/gravedanger/index.phtml',
      },
      {
        title: 'Kiko Pop',
        description: 'Free food for the homeless',
        src: 'https://images.neopets.com/items/kik_cook_treats.gif',
        href: 'http://www.neopets.com/worlds/kiko/kpop/',
      },
    ]
  },
  {
    title: 'Wheels',
    items: [
      {
        title: 'Wheel of Mediocrity',
        description: 'Free food for the homeless',
        src: 'https://images.neopets.com/wheels/new/mediocrity.jpg',
        href: 'http://www.neopets.com/prehistoric/mediocrity.phtml',
      },
      {
        title: 'Wheel of Excitement',
        description: 'Free food for the homeless',
        src: 'https://images.neopets.com/wheels/new/excitement.jpg',
        href: 'http://www.neopets.com/faerieland/wheel.phtml',
      },
      {
        title: 'Wheel of Misfortune',
        description: 'Free food for the homeless',
        src: 'https://images.neopets.com/wheels/new/misfortune.jpg',
        href: 'http://www.neopets.com/halloween/wheel/index.phtml',
      },
      {
        title: 'Wheel of Knowledge',
        description: 'Free food for the homeless',
        src: 'https://images.neopets.com/wheels/new/knowledge.jpg',
        href: 'http://www.neopets.com/medieval/knowledge.phtml',
      },
      {
        title: 'Wheel of Monotony',
        description: 'Free food for the homeless',
        src: 'https://images.neopets.com/wheels/new/monotony.jpg',
        href: 'http://www.neopets.com/prehistoric/monotony/monotony.phtml',
      },
      {
        title: 'Wheel of Extravagance',
        description: 'Free food for the homeless',
        src: 'https://images.neopets.com/wheels/h5/extravagance/images/wheel-icon.png',
        href: 'http://www.neopets.com/desert/extravagance.phtml',
      },
      {
        title: 'NC Archives Wheel',
        description: 'Free food for the homeless',
        src: 'https://images.neopets.com/items/mall_fc_wheel.gif',
        href: 'http://www.neopets.com/mall/wheel/',
      },
    ],
  },
  {
    title: 'Scratchcards',
    items: [
      {
      title: 'Winter Kiosk',
      description: 'Free food for the homeless',
      src: 'https://images.neopets.com/games/clicktoplay/screenshot_thumbnail_193_1_v1.png',
      href: 'http://www.neopets.com/winter/kiosk.phtml',
    },
    {
      title: 'Spooky Kiosk',
      description: 'Free food for the homeless',
      src: 'https://images.neopets.com/battledome/opponent_pics/85.gif',
      href: 'http://www.neopets.com/halloween/scratch.phtml',
    },
    {
      title: 'Desert Kiosk',
      description: 'Free food for the homeless',
      src: 'https://images.neopets.com/shopkeepers/ldsc_cybunny.gif',
      href: 'http://www.neopets.com/desert/sc/kiosk.phtml',
    },
    ],
  },
  {
    title: 'essentials',
    items: [
      {
      title: 'Tombola',
      description: 'Free food for the homeless',
      src: 'https://images.neopets.com/items/tiki_keychain.gif',
      href: 'http://www.neopets.com/island/tombola.phtml',
    },
    {
      title: 'Snowager',
      description: 'Free food for the homeless',
      src: 'https://images.neopets.com/items/toy_snowager_plushie.gif',
      href: 'http://www.neopets.com/winter/snowager.phtml',
    },
    {
      title: 'Guess the Marrow',
      description: 'Free food for the homeless',
      src: 'https://images.neopets.com/items/marrow_veg.gif',
      href: 'http://www.neopets.com/medieval/guessmarrow.phtml',
    },
    {
      title: 'Wise Old King',
      description: 'Free food for the homeless',
      src: 'https://images.neopets.com/items/plu_skeith_hagan.gif',
      href: 'http://www.neopets.com/medieval/wiseking.phtml',
    },
    {
      title: 'Grumpy Old King',
      description: 'Free food for the homeless',
      src: 'https://images.neopets.com/items/toy_plushie_skarl.gif',
      href: 'http://www.neopets.com/medieval/grumpyking.phtml',
    },
    {
      title: 'Deserted Tomb',
      description: 'Free food for the homeless',
      src: 'https://images.neopets.com/items/plu_halloween_lizark.gif',
      href: 'http://www.neopets.com/worlds/geraptiku/tomb.phtml',
    },
    {
      title: 'Fruit Machine',
      description: 'Free food for the homeless',
      src: 'https://images.neopets.com/items/plu_fruitmachine_kau.gif',
      href: 'http://www.neopets.com/desert/fruitmachine.phtml',
    },
    {
      title: 'Coltzan\'s Shrine',
      description: 'Free food for the homeless',
      src: 'https://images.neopets.com/items/plu_lupe_coltzan.gif',
      href: 'http://www.neopets.com/desert/shrine.phtml',
    },
    {
      title: 'Deadly Dice',
      description: 'Free food for the homeless',
      src: 'https://images.neopets.com/items/plu_von_roo.gif',
      href: 'http://www.neopets.com/worlds/deadlydice.phtml',
    },
    {
      title: 'Kreludor Meteor',
      description: 'Free food for the homeless',
      src: 'https://images.neopets.com/items/baby_space_fungus_plushie.gif',
      href: 'http://www.neopets.com/moon/meteor.phtml',
    },
    {
      title: 'TDMBGPOP',
      description: 'Free food for the homeless',
      src: 'https://images.neopets.com/items/plu_TDMBGPOP_replica.gif',
      href: 'http://www.neopets.com/faerieland/tdmbgpop.phtml',
    },
    {
      title: 'Ye Olde Fishing Vortex',
      description: 'Free food for the homeless',
      src: 'https://images.neopets.com/items/plu_magic_lesserspottedfish.gif',
      href: 'http://www.neopets.com/water/fishing.phtml',
    },
    {
      title: 'Hide n\' Seek',
      description: 'Free food for the homeless',
      src: 'https://images.neopets.com/items/toy_kacheekblue.gif',
      href: 'http://www.neopets.com/games/hidenseek.phtml',
    },
    {
      title: 'Quasalan Expellibox',
      description: 'Free food for the homeless',
      src: 'https://images.neopets.com/items/toy_scarab_plushie.gif',
      href: 'http://www.neopets.com/games/giveaway/giveaway_game.phtml',
    },
    {
      title: 'Lunar Temple',
      description: 'Free food for the homeless',
      src: 'https://images.neopets.com/items/toy_gnorbu_blue.gif',
      href: 'http://www.neopets.com/shenkuu/lunar/',
    },
    {
      title: 'Potato Counter',
      description: 'Free food for the homeless',
      src: 'https://images.neopets.com/items/plu_potato.gif',
      href: 'http://www.neopets.com/medieval/potatocounter.phtml',
    },
    {
      title: 'Forgotten Shore',
      description: 'Free food for the homeless',
      src: 'https://images.neopets.com/items/plu_blumaroopirate.gif',
      href: 'http://www.neopets.com/pirates/forgottenshore.phtml',
    },
    {
      title: 'Healing Springs',
      description: 'Free food for the homeless',
      src: 'https://images.neopets.com/items/plu_bori_faerie.gif',
      href: 'http://www.neopets.com/faerieland/springs.phtml',
    },
    {
      title: 'Battledome Daily Prizes',
      description: 'Free food for the homeless',
      src: 'https://images.neopets.com/items/toy_battlefaerie_plushie.gif',
      href: 'http://www.neopets.com/dome/',
    },
    ]
  },
  {
    title: 'Neopoints',
    items: [
      {
      title: 'Smuggler\s Cove',
      description: 'Free food for the homeless',
      src: 'https://images.neopets.com/items/plu_bruce_smuggler.gif',
      href: 'http://www.neopets.com/pirates/smugglerscove.phtml',
    },
    {
      title: 'Garage Sale',
      description: 'Free food for the homeless',
      src: 'https://images.neopets.com/items/blueigloo_chia_doll.gif',
      href: 'http://www.neopets.com/winter/igloo.phtml',
    },
    {
      title: 'Buried Treasure',
      description: 'Free food for the homeless',
      src: 'https://images.neopets.com/items/plu_krawk_pirate.gif',
      href: 'http://www.neopets.com/pirates/buriedtreasure/index.phtml',
    },
    {
      title: 'Poogle Racing',
      description: 'Free food for the homeless',
      src: 'https://images.neopets.com/items/plu_poogle_faerie.gif',
      href: 'http://www.neopets.com/faerieland/poogleracing.phtml',
    },
    {
      title: 'Turdle Racing',
      description: 'Free food for the homeless',
      src: 'https://images.neopets.com/items/toy_turdle_plushie.gif',
      href: 'http://www.neopets.com/medieval/turdleracing.phtml',
    },
    {
      title: 'Lever of Doom',
      description: 'Free food for the homeless',
      src: 'https://images.neopets.com/items/plu_robot_kougra.gif',
      href: 'http://www.neopets.com/space/strangelever.phtml',
    },
    {
      title: 'Grarrl Keno',
      description: 'Free food for the homeless',
      src: 'https://images.neopets.com/items/toy_grarrl_red.gif',
      href: 'http://www.neopets.com/prehistoric/keno.phtml',
    },
    {
      title: 'Neopian Lottery',
      description: 'Free food for the homeless',
      src: 'https://images.neopets.com/items/plu_evil_redscorchio.gif',
      href: 'http://www.neopets.com/games/lottery.phtml',
    },
    {
      title: 'Test Your Strength',
      description: 'Free food for the homeless',
      src: 'https://images.neopets.com/items/plu_mynci_halloween.gif',
      href: 'http://www.neopets.com/halloween/strtest/index.phtml',
    },
    {
      title: 'Wishing Well',
      description: 'Free food for the homeless',
      src: 'https://images.neopets.com/items/luckycoinplushie.gif',
      href: 'http://www.neopets.com/wishing.phtml',
    },
    {
      title: 'Coconut Shy',
      description: 'Free food for the homeless',
      src: 'https://images.neopets.com/items/toy_coconutshy_quiggle.gif',
      href: 'http://www.neopets.com/halloween/coconutshy.phtml',
    },
    {
      title: 'Bagatelle',
      description: 'Free food for the homeless',
      src: 'https://images.neopets.com/items/toy_bagalupe_plushie.gif',
      href: 'http://www.neopets.com/halloween/bagatelle.phtml',
    },
    {
      title: 'Cork Gun Gallery',
      description: 'Free food for the homeless',
      src: 'https://images.neopets.com/items/plu_ddY21_punchbag_bob.gif',
      href: 'http://www.neopets.com/halloween/corkgun.phtml',
    },
    {
      title: 'Double or Nothing',
      description: 'Free food for the homeless',
      src: 'https://images.neopets.com/items/plu_skeith_snargan.gif',
      href: 'http://www.neopets.com/medieval/doubleornothing.phtml',
    },
    {
      title: 'Kiss the Mortog',
      description: 'Free food for the homeless',
      src: 'https://images.neopets.com/items/plu_advc2013_mortogplush.gif',
      href: 'http://www.neopets.com/medieval/kissthemortog.phtml',
    },
    {
      title: 'Cheeseroller',
      description: 'Free food for the homeless',
      src: 'https://images.neopets.com/items/plu_techo_cheeseroller.gif',
      href: 'http://www.neopets.com/medieval/cheeseroller.phtml',
    },
    {
      title: 'Pick Your Own',
      description: 'Free food for the homeless',
      src: 'https://images.neopets.com/items/gelert_plush_yellow.gif',
      href: 'http://www.neopets.com/medieval/pickyourown_index.phtml',
    },
    {
      title: 'Food Club',
      description: 'Free food for the homeless',
      src: 'https://images.neopets.com/items/plu_kyrii_pirate.gif',
      href: 'http://www.neopets.com/pirates/foodclub.phtml?type=bet',
    },
    {
      title: 'Stock Market',
      description: 'Free food for the homeless',
      src: 'https://images.neopets.com/items/yellowchiadoll.gif',
      href: 'http://www.neopets.com/stockmarket.phtml?type=list&bargain=true',
    },
    {
      title: 'Snow Wars',
      description: 'Free food for the homeless',
      src: 'https://images.neopets.com/items/plu_abominable_snowball.gif',
      href: 'http://www.neopets.com/games/game.phtml?game_id=55',
    },
    {
      title: 'Almost Abandoned Attic',
      description: 'Free food for the homeless',
      src: 'https://images.neopets.com/items/plu_aisha_ghost.gif',
      href: 'http://www.neopets.com/halloween/garage.phtml',
    },
    {
      title: 'Faerie Caverns',
      description: 'Free food for the homeless',
      src: 'https://images.neopets.com/items/plu_shoyru_faerie.gif',
      href: 'http://www.neopets.com/faerieland/caverns/index.phtml',
    },
    {
      title: 'Cheat!',
      description: 'Free food for the homeless',
      src: '/vercel.svg',
      href: 'http://www.neopets.com/games/game.phtml?game_id=109',
    },
    {
      title: 'Scorchy Slots',
      description: 'Free food for the homeless',
      src: '/vercel.svg',
      href: 'http://www.neopets.com/games/slots.phtml',
    },
    {
      title: 'Gormball',
      description: 'Free food for the homeless',
      src: '/vercel.svg',
      href: 'http://www.neopets.com/space/gormball.phtml',
    },
    {
      title: 'Dice-a-Roo',
      description: 'Free food for the homeless',
      src: '/vercel.svg',
      href: 'http://www.neopets.com/games/game.phtml?game_id=10',
    },
    {
      title: 'Toy Repair Shop',
      description: 'Free food for the homeless',
      src: '/vercel.svg',
      href: 'http://www.neopets.com/winter/brokentoys.phtml',
    },
    ],
  },
  {
    title: 'training',
    items: [
      {
        title: 'Codestone Training',
        description: 'Free food for the homeless',
        src: '/vercel.svg',
        href: 'http://www.neopets.com/island/training.phtml',
      },
      {
        title: 'Dubloon Training',
        description: 'Free food for the homeless',
        src: '/vercel.svg',
        href: 'http://www.neopets.com/pirates/academy.phtml',
      },
      {
        title: 'Ninja Training School',
        description: 'Free food for the homeless',
        src: '/vercel.svg',
        href: 'http://www.neopets.com/island/fight_training.phtml',
      },
    ],
  },
  {
    title: 'Updates',
    items: [
      {
        title: 'Neopian News',
        description: 'Free food for the homeless',
        src: '/vercel.svg',
        href: 'http://www.neopets.com/nf.phtml',
      },
      {
        title: 'Neopian Times',
        description: 'Free food for the homeless',
        src: '/vercel.svg',
        href: 'http://www.neopets.com/ntimes/',
      },
    ]
  },
  {
    title: 'Other',
    items: [
      {
        title: 'Turmaculus',
        description: 'Free food for the homeless',
        src: '/vercel.svg',
        href: 'http://www.neopets.com/medieval/turmaculus.phtml',
      },
      {
        title: 'Symol Hole',
        description: 'Free food for the homeless',
        src: '/vercel.svg',
        href: 'http://www.neopets.com/medieval/symolhole.phtml',
      },
      {
        title: 'Laboratory Ray',
        description: 'Free food for the homeless',
        src: '/vercel.svg',
        href: 'http://www.neopets.com/lab2.phtml',
      },
      {
        title: 'PetPet Laboratory Ray',
        description: 'Free food for the homeless',
        src: '/vercel.svg',
        href: 'http://www.neopets.com/petpetlab.phtml',
      },
      {
        title: 'Stock Market',
        description: 'Free food for the homeless',
        src: '/vercel.svg',
        href: 'http://www.neopets.com/stockmarket.phtml?type=portfolio',
      },
      {
        title: 'Trading Post',
        description: 'Free food for the homeless',
        src: '/vercel.svg',
        href: 'http://www.neopets.com/island/tradingpost.phtml',
      },
      {
        title: 'Auction House',
        description: 'Free food for the homeless',
        src: '/vercel.svg',
        href: 'http://www.neopets.com/auctions.phtml',
      },
      {
        title: 'Employment Agency',
        description: 'Free food for the homeless',
        src: '/vercel.svg',
        href: 'http://www.neopets.com/faerieland/employ/employment.phtml',
      },
      {
        title: 'Neolodge',
        description: 'Free food for the homeless',
        src: '/vercel.svg',
        href: 'http://www.neopets.com/neolodge.phtml',
      },
      {
        title: 'Featured Band',
        description: 'Free food for the homeless',
        src: '/vercel.svg',
        href: 'http://www.neopets.com/prehistoric/ticketbooth.phtml',
      },
      {
        title: 'Haiku',
        description: 'Free food for the homeless',
        src: '/vercel.svg',
        href: 'http://www.neopets.com/island/haiku/haiku.phtml',
      },
      {
        title: 'Island Mystic',
        description: 'Free food for the homeless',
        src: '/vercel.svg',
        href: 'http://www.neopets.com/island/mystichut.phtml',
      },
      {
        title: 'Golden Dubloon',
        description: 'Free food for the homeless',
        src: '/vercel.svg',
        href: 'http://www.neopets.com/pirates/restaurant.phtml',
      },
      {
        title: 'Kelp Restaurant',
        description: 'Free food for the homeless',
        src: '/vercel.svg',
        href: 'http://www.neopets.com/water/restaurant.phtml',
      },
      {
        title: 'Merry Go Round',
        description: 'Free food for the homeless',
        src: '/vercel.svg',
        href: 'http://www.neopets.com/worlds/roo/merrygoround.phtml',
      },
      {
        title: 'Tiki Tours',
        description: 'Free food for the homeless',
        src: '/vercel.svg',
        href: 'http://www.neopets.com/island/tikitours.phtml',
      },
      {
        title: 'Neomail',
        description: 'Free food for the homeless',
        src: '/vercel.svg',
        href: 'http://www.neopets.com/neomessages.phtml',
      },
      {
        title: 'Tarla\'s Shop',
        description: 'Free food for the homeless',
        src: '/vercel.svg',
        href: 'http://www.neopets.com/winter/shopofmystery.phtml',
      },
      {
        title: 'Tarla\'s Treasures',
        description: 'Free food for the homeless',
        src: '/vercel.svg',
        href: 'http://www.neopets.com/freebies/tarlastoolbar.phtml',
      },
      {
        title: 'Multiplayer Competition',
        description: 'Free food for the homeless',
        src: '/vercel.svg',
        href: 'http://www.neopets.com/games/lobby/mp_comp.phtml',
      },
      {
        title: 'Kadoatery',
        description: 'Free food for the homeless',
        src: '/vercel.svg',
        href: 'http://www.neopets.com/games/kadoatery/index.phtml',
      },
      {
        title: 'Neggery',
        description: 'Free food for the homeless',
        src: '/vercel.svg',
        href: 'http://www.neopets.com/winter/neggery.phtml',
      },
      {
        title: 'Plushie Tycoon',
        description: 'Free food for the homeless',
        src: '/vercel.svg',
        href: 'http://www.neopets.com/games/tycoon/index.phtml',
      },
      {
        title: 'Magma Pool',
        description: 'Free food for the homeless',
        src: '/vercel.svg',
        href: 'http://www.neopets.com/magma/pool.phtml',
      },
      {
        title: 'Tangor\'s Workshop',
        description: 'Free food for the homeless',
        src: '/vercel.svg',
        href: 'http://www.neopets.com/magma/workshop.phtml',
      },
      {
        title: 'Cliffhanger',
        description: 'Free food for the homeless',
        src: '/vercel.svg',
        href: 'http://www.neopets.com/games/cliffhanger/cliffhanger.phtml',
      },
      {
        title: 'NeoQuest',
        description: 'Free food for the homeless',
        src: '/vercel.svg',
        href: 'http://www.neopets.com/games/neoquest/neoquest.phtml',
      },
      {
        title: 'NeoQuest II',
        description: 'Free food for the homeless',
        src: '/vercel.svg',
        href: 'http://www.neopets.com/games/nq2/index.phtml',
      },
      {
        title: 'NeoCola Machine',
        description: 'Free food for the homeless',
        src: '/vercel.svg',
        href: 'http://www.neopets.com/moon/neocola.phtml',
      },
      {
        title: 'Alien Aisha Vending Machine',
        description: 'Free food for the homeless',
        src: '/vercel.svg',
        href: 'http://www.neopets.com/vending.phtml',
      },
    ],
  },
  {
    title: 'Quests',
    items: [
      {
        title: 'Illusen\'s Glade',
        description: 'Free food for the homeless',
        src: '/vercel.svg',
        href: 'http://www.neopets.com/medieval/earthfaerie.phtml',
      },
      {
        title: 'Jhudora\'s Bluff',
        description: 'Free food for the homeless',
        src: '/vercel.svg',
        href: 'http://www.neopets.com/faerieland/darkfaerie.phtml',
      },
      {
        title: 'Snow Faerie Quests',
        description: 'Free food for the homeless',
        src: '/vercel.svg',
        href: 'http://www.neopets.com/winter/snowfaerie.phtml',
      },
      {
        title: 'Faerie Quests',
        description: 'Free food for the homeless',
        src: '/vercel.svg',
        href: 'http://www.neopets.com/quests.phtml',
      },
      {
        title: 'Brain Tree Quests',
        description: 'Free food for the homeless',
        src: '/vercel.svg',
        href: 'http://www.neopets.com/halloween/braintree.phtml',
      },
      {
        title: 'Esophagor\'s Quests',
        description: 'Free food for the homeless',
        src: '/vercel.svg',
        href: 'http://www.neopets.com/halloween/esophagor.phtml',
      },
      {
        title: 'Edna\'s Quests',
        description: 'Free food for the homeless',
        src: '/vercel.svg',
        href: 'http://www.neopets.com/halloween/witchtower.phtml',
      },
      {
        title: 'Kitchen Quests',
        description: 'Free food for the homeless',
        src: '/vercel.svg',
        href: 'http://www.neopets.com/island/kitchen.phtml',
      },
      {
        title: 'Coincidence',
        description: 'Free food for the homeless',
        src: '/vercel.svg',
        href: 'http://www.neopets.com/magma/portal/ship.phtml',
      },
    ],
  },
  {
    title: 'contests',
    items: [
      {
        title: 'Lenny Conundrum',
        description: 'Free food for the homeless',
        src: '/vercel.svg',
        href: 'http://www.neopets.com/games/conundrum.phtml',
      },
      {
        title: 'Neohome',
        description: 'Free food for the homeless',
        src: '/vercel.svg',
        href: 'http://www.neopets.com/homespotlight.phtml',
      },
      {
        title: 'Gallery',
        description: 'Free food for the homeless',
        src: '/vercel.svg',
        href: 'http://www.neopets.com/gallery.phtml',
      },
      {
        title: 'Gourmet Club',
        description: 'Free food for the homeless',
        src: '/vercel.svg',
        href: 'http://www.neopets.com/gourmet_club.phtml',
      },
      {
        title: 'Site Spotlight',
        description: 'Free food for the homeless',
        src: '/vercel.svg',
        href: 'http://www.neopets.com/sitespotlight.phtml',
      },
      {
        title: 'PetPet Spotlight',
        description: 'Free food for the homeless',
        src: '/vercel.svg',
        href: 'http://www.neopets.com/petpetspotlight.phtml',
      },
      {
        title: 'Pet Spotlight',
        description: 'Free food for the homeless',
        src: '/vercel.svg',
        href: 'http://www.neopets.com/spotlight.phtml',
      },
      {
        title: 'Art Gallery',
        description: 'Free food for the homeless',
        src: '/vercel.svg',
        href: 'http://www.neopets.com/art/gallery.phtml',
      },
      {
        title: 'Poetry',
        description: 'Free food for the homeless',
        src: '/vercel.svg',
        href: 'http://www.neopets.com/contributions_poems.phtml',
      },
      {
        title: 'Better Than You',
        description: 'Free food for the homeless',
        src: '/vercel.svg',
        href: 'http://www.neopets.com/games/betterthanyou.phtml',
      },
      {
        title: 'Neopian Times',
        description: 'Free food for the homeless',
        src: '/vercel.svg',
        href: 'http://www.neopets.com/ntimes/nt_submit.phtml',
      },
      {
        title: 'Beauty Contest',
        description: 'Free food for the homeless',
        src: '/vercel.svg',
        href: 'http://www.neopets.com/beauty/index.phtml',
      },
      {
        title: 'Caption Contest',
        description: 'Free food for the homeless',
        src: '/vercel.svg',
        href: 'http://www.neopets.com/games/new_caption.phtml',
      },
      {
        title: 'Mystery Pic',
        description: 'Free food for the homeless',
        src: '/vercel.svg',
        href: 'http://www.neopets.com/games/mysterypic.phtml',
      },
      {
        title: 'Story Telling',
        description: 'Free food for the homeless',
        src: '/vercel.svg',
        href: 'http://www.neopets.com/art/storytell.phtml',
      },
      {
        title: 'Customisation',
        description: 'Free food for the homeless',
        src: '/vercel.svg',
        href: 'http://www.neopets.com/spotlights/custompet/index.phtml',
      },
      {
        title: 'User Lookups',
        description: 'Free food for the homeless',
        src: '/vercel.svg',
        href: 'http://www.neopets.com/ul_spotlight.phtml',
      },
    ]
  }
]
